const fs = require('fs');
const path = require('path');

// 1. Try to read from local .env if it exists
let env = {};
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  const fileContent = fs.readFileSync(envPath, 'utf-8');
  fileContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
      const parts = trimmed.split('=');
      const key = parts[0].trim();
      const val = parts.slice(1).join('=').trim();
      env[key] = val;
    }
  });
}

// 2. Read from process.env (Vercel builds will use this) or fallback to .env loaded variables
const apiKey = process.env.FIREBASE_API_KEY || env.FIREBASE_API_KEY || "";
const projectId = process.env.FIREBASE_PROJECT_ID || env.FIREBASE_PROJECT_ID || "";
const appId = process.env.FIREBASE_APP_ID || env.FIREBASE_APP_ID || "";
const authDomain = process.env.FIREBASE_AUTH_DOMAIN || env.FIREBASE_AUTH_DOMAIN || (projectId ? `${projectId}.firebaseapp.com` : "");
const storageBucket = process.env.FIREBASE_STORAGE_BUCKET || env.FIREBASE_STORAGE_BUCKET || (projectId ? `${projectId}.firebasestorage.app` : "");
const messagingSenderId = process.env.FIREBASE_MESSAGING_SENDER_ID || env.FIREBASE_MESSAGING_SENDER_ID || "";

const cloudName = process.env.CLOUDINARY_CLOUD_NAME || env.CLOUDINARY_CLOUD_NAME || "";
const uploadPreset = process.env.CLOUDINARY_UPLOAD_PRESET || env.CLOUDINARY_UPLOAD_PRESET || "";

// 3. Write config.js containing the values
const configContent = `// Automatically generated by build.js. Do not modify or commit!
window.ENV_CONFIG = {
  firebase: {
    apiKey: "${apiKey}",
    authDomain: "${authDomain}",
    projectId: "${projectId}",
    storageBucket: "${storageBucket}",
    messagingSenderId: "${messagingSenderId}",
    appId: "${appId}"
  },
  cloudinary: {
    cloudName: "${cloudName}",
    uploadPreset: "${uploadPreset}"
  }
};

export const FIREBASE_CONFIG = window.ENV_CONFIG.firebase;
export const CLOUDINARY_CONFIG = window.ENV_CONFIG.cloudinary;
export const isMobile = typeof navigator !== 'undefined' ? (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || window.innerWidth < 768) : false;
export const isLowEnd = typeof navigator !== 'undefined' && navigator.deviceMemory ? navigator.deviceMemory <= 2 : false;
export const prefersReducedMotion = typeof window !== 'undefined' ? window.matchMedia('(prefers-reduced-motion: reduce)').matches : false;

export function getConfig() {
  const localFbApiKey = typeof localStorage !== 'undefined' ? localStorage.getItem('fb_apiKey') : null;
  const localFbProjId = typeof localStorage !== 'undefined' ? localStorage.getItem('fb_projectId') : null;
  const localFbAppId = typeof localStorage !== 'undefined' ? localStorage.getItem('fb_appId') : null;
  const localCloudName = typeof localStorage !== 'undefined' ? localStorage.getItem('cl_cloudName') : null;
  const localUploadPreset = typeof localStorage !== 'undefined' ? localStorage.getItem('cl_uploadPreset') : null;

  return {
    firebase: {
      apiKey: localFbApiKey || FIREBASE_CONFIG.apiKey,
      projectId: localFbProjId || FIREBASE_CONFIG.projectId,
      appId: localFbAppId || FIREBASE_CONFIG.appId,
      authDomain: (localFbProjId || FIREBASE_CONFIG.projectId) ? \`\${localFbProjId || FIREBASE_CONFIG.projectId}.firebaseapp.com\` : ""
    },
    cloudinary: {
      cloudName: localCloudName || CLOUDINARY_CONFIG.cloudName,
      uploadPreset: localUploadPreset || CLOUDINARY_CONFIG.uploadPreset
    }
  };
}
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), configContent, 'utf-8');
console.log('config.js successfully generated!');

